version: '3.8'

services:

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
        - 127.0.0.1:9000:9000
        - 127.0.0.1:8123:8123
    volumes:
      - ./data:/var/lib/clickhouse/
      - ./log:/var/log/clickhouse-server/
    ulimits:
        nofile:
            soft: 262144
            hard: 262144
    restart: unless-stopped
    
